VegeFood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
     path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('carro/', include('carro.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('pedidos/', include('pedidos.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path

from . views import *
from core.urls import *
app_name="carro"

urlpatterns = [ 

    path('cart/add/<int:id>/', cart_add, name="cart_add"),
    path('cart/item_clear/<int:id>/', item_clear, name="item_clear"),
    path('cart/item_increment/<int:id>/', item_increment, name="item_increment"),
    path('cart/item_decrement/<int:id>/', item_decrement, name="item_decrement"),
    path('cart/cart_clear/', cart_clear, name="cart_clear"),
    path('cart/cart-detail/', cart_detail, name="cart_detail"),


]

core/urls.py
from django.urls import path, include
from .views import *
from core import views
from rest_framework import routers
from carro.views import *
## VIEWS -> URLS -> HTML

router = routers.DefaultRouter()
router.register('productos', ProductoViewset)
router.register('TipoProductos', TipoProductoViewset)
router.register('Contacto', ContactoViewset)
router.register('Compra', CompraViewset)

urlpatterns = [
    path('api/', include(router.urls)),
    path('',index, name="index"),
    path('apiindex/',apiindex, name="apiindex"),
    path('about/',about, name="about"),
    path('cart/',cart, name="cart"),
    path('checkout/',checkout, name="checkout"),
    path('contact/',contact, name="contact"),
    path('news/',news, name="news"),
    path('shop/',shop, name="shop"),
    path('single-news/',singlenews, name="singlenews"),
    path('single-product/<id>/',singleproduct, name="singleproduct"),
    path('agregar-producto/',agregar_producto, name="agregar_producto"),
    path('listar-productos/',listar_productos, name="listar_productos"),
    path('modificar-productos/<id>/',modificar_productos, name="modificar_productos"),
    path('eliminar-productos/<id>/',eliminar_productos, name="eliminar_productos"),
    path('registro/',registro, name="registro"),
    path('gallery/',gallery, name="gallery"),
    path('detallepedido/<id>/', detallepedido, name="detallepedido"),
    path('status/', status, name='status'),
    path('subscripcion/', subscripcion, name="subscripcion"),
    path('ordercomplete/', ordercomplete, name="ordercomplete"),
    path('usuario/', usuario, name='usuario'),
    path('carro/', include('carro.urls', namespace='carro')),
    path('donacion/', donacion, name='donacion'),
    path('cambiar_estado_pedido/<int:pedido_id>/', views.cambiar_estado_pedido, name='cambiar_estado_pedido'),
    path('contacto_admin/', contacto_admin, name='contacto_admin'),
    #usuarios
    path('administracion_user/', administracion_user, name='administracion_user'),
    path('crear_usuario/', views.crear_usuario, name='crear_usuario'),
    path('modificar_user/<int:usuario_id>/', views.modificar_user, name='modificar_user'),
    path('eliminar_usuario/<int:usuario_id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('registrar-entrega/', views.registrar_entrega_pedido, name='registrar_entrega_pedido'),
    path('lista_entregas/', lista_entregas, name='lista_entregas'),
    path('listar_user/', listar_user, name='listar_user'),



    path('recuperar-contraseña/', views.recuperar_contraseña_view, name='recuperar_contraseña'),
    path('ver_pedidos_bode/', ver_pedidos_bode, name='ver_pedidos_bode'),

 #Carrito



    #CRUD
   
    path('suscribir/<id>/', agregar_suscriptor, name="suscribir"),
    path('quitar-usuario/<id>/', quitar_usuario_de_grupo, name='quitar_usuario_de_grupo'),

]

pedidos/urls.py
from django.urls import path
from .views import *

app_name = 'pedidos'

urlpatterns = [

    path("", procesar_pedido , name="procesar_pedido"),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here. 


opciones_consulta = [
        [0, "Consulta"],
        [1, "Reclamo"],
        [2, "Sugerencia"],
        [3, "Felicidades"]
    ]
#TABLA TIPO PRODUCTO

class tipoProducto(models.Model):
    descripcion = models.CharField(max_length=50)

    def __str__(self):
        return self.descripcion

#TABLA PRODUCTO

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    stock = models.IntegerField()
    tipo = models.ForeignKey(tipoProducto, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="productos", null=True)

    def __str__(self):
        return self.nombre

   

class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consulta)
    mensaje = models.TextField()
    avisos = models.BooleanField()

    def __str__(self):
        return self.nombre 

class Compra(models.Model):
    fecha = models.DateTimeField(auto_now_add=True)
    usuario_id = models.IntegerField()
    

    def __str__(self):
        return self.nombre 

core/views.py
from django.shortcuts import redirect, render, get_list_or_404, get_object_or_404
from django.urls import reverse
from .models import Producto
from .forms import *
from django.contrib import messages
from rest_framework import viewsets
from .serializers import *
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.core.paginator import Paginator
from django.http import Http404, HttpResponseForbidden
from django.contrib.auth import authenticate, login
import requests
from django.contrib.auth.models import User, Group
from django.dispatch import receiver 
from django.db.models.signals import post_save
from pedidos.models import *
from carro.carro import Carro
from carro.views import *

#funcion generica que valida el grupo
def grupo_requerido(nombre_grupo):
    def decorator(view_func):
        @user_passes_test(lambda user : user.groups.filter(name=nombre_grupo).exists())
        def wrapper(request, *args, **kwargs):
            return view_func(request, *args, **kwargs)
        return wrapper
    return decorator
# serializers

class ProductoViewset(viewsets.ModelViewSet):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializers 

class TipoProductoViewset(viewsets.ModelViewSet):
    queryset = tipoProducto.objects.all()
    serializer_class = TipoProductoSerializers 

class ContactoViewset(viewsets.ModelViewSet):
    queryset = Contacto.objects.all()
    serializer_class = ContactoSerializers     

class CompraViewset(viewsets.ModelViewSet):
    queryset = Compra.objects.all()
    serializer_class = CompraSerializers  
# Create your views here.

def index(request):
    productos = Producto.objects.all()
    page = request.GET.get('page', 1)
    try:
        paginator = Paginator(productos, 3)
        productos = paginator.page(page)
    except:
        raise Http404 

    user_is_contador = request.user.groups.filter(name='contador').exists()

    data ={
    'entity' : productos,
    'paginator' : paginator,
    'user_is_contador': user_is_contador
  }
    return render(request, 'core/index.html', data)
#API
def apiindex(request):
    respuesta = requests.get('http://127.0.0.1:8000/api/productos/')
    respuesta2 = requests.get('https://rickandmortyapi.com/api/characters/')    
    productos = respuesta.json
    aux = respuesta2.json()
    personajes = aux['results']

    data ={
    'listaProducto' : productos,
    'personajes': personajes,
  }
    return render(request, 'core/apiindex.html', data)

def indexapi(request):
    respuesta = requests.get('http://127.0.0.1:8000/api/TipoProductos/')
    respuesta2 = requests.get('http://mindicator.cl/api/')
    respuesta3 = requests.get('https://rickandmortyapi.com/api/characters/')

    #TRANSFORMACION A JSON
    productos = respuesta.json()
    monedas = respuesta2.json()
    aux = respuesta3.json()
    personajes = aux['results']

    data = {
        'listaProducto': productos,
        'moneda': monedas,
        'personajes': personajes,
    }

    return render(request, 'core/indexapi.html', data)


def about(request):
    return render(request, ('core/about.html'))


def donacion(request):
    return render(request, ('core/donacion.html'))



def cart(request):

    respuesta = requests.get('https://mindicador.cl/api/dolar').json()
    valor_usd = respuesta['serie'][0]['valor']
    valor_carrito = 20000 #ciclo for para sumar todos los productos del carrito
    #convertimos de clp a usd
    valor_total = valor_carrito/valor_usd
    data = {
        'dolar' : round(valor_total, 2)
    }

    return render(request,'core/cart.html', data)

def checkout(request):
    return render(request, ('core/checkout.html'))

@grupo_requerido('usuario')
def contact(request):
    data = {
        'form': ContactoForm()
    }

    if request.method == 'POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "contacto enviado"
        else:
            data['form'] = formulario
        
    return render(request, 'core/contact.html', data)


@permission_required('core.add_producto')
def agregar_producto(request):
    data = {
        'form' : ProductoForm()
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES) # RECIBE TODA LA INFO DEL FORMULARIO
        if formulario.is_valid():
            formulario.save() # COMMIT, INSERT INTO .........
            #data['msj'] = "Producto guardado correctamente"
            messages.success(request, "Producto almacenado correctamente")  
            
    return render(request, 'core/agregar.html', data)

@login_required
 
@permission_required('core.view_producto')
def listar_productos(request):
    productos = Producto.objects.all()
    page = request.GET.get('page', 1)
    try:
        paginator = Paginator(productos, 5)
        productos = paginator.page(page)
    except:
        raise Http404

    data ={
    'entity' : productos,
    'paginator' : paginator
  }
    return render(request, 'core/listar.html', data )

@login_required
@permission_required('core.change_producto')
def modificar_productos(request, id):
    producto = Producto.objects.get(id=id)
    data = {
        'form' : ProductoForm(instance=producto)
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES) # RECIBE EL CONTENIDO DEL FORMULARIO
        if formulario.is_valid():
            formulario.save() # INSERT
            messages.success(request , "Editado Correctamente")
            return redirect(to="listar_productos")
        else :
            data['form'] = formulario

    return render (request,'core/modificar.html', data)

@login_required
@permission_required('core.delete_producto')
def eliminar_productos(request, id):
    producto = Producto.objects.get(id=id)
    producto.delete()
    messages.success(request , "Eliminado Correctamente")

    return redirect(to="listar_productos")

def news(request):
    return render(request, ('core/news.html'))


def shop(request):
    productos = Producto.objects.all()
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(productos, 3)
        productos = paginator.page(page)
    except:
        raise Http404 

    data = {
        'entity': productos,
        'paginator' : paginator

    }
    return render(request, 'core/shop.html', data)


def singlenews(request,):
    return render(request, ('core/single-news.html'))

def singleproduct(request, id):
    productos = Producto.objects.all()
    page = request.GET.get('page', 1)
    try:
        paginator = Paginator(productos, 1)
        productos = paginator.page(page)
    except:
        raise Http404 


    data ={
    'entity' : productos,
    'paginator' : paginator
  }
    return render(request, 'core/single-product.html', data)


def registro(request):
    if request.method == 'POST':
        f = CustomUserCreationForm(request.POST)
        if f.is_valid():
            usuario = f.save()
            messages.success(request, 'Cuenta Creada correctamente')
            
            login(request, usuario)

            cliente = User.objects.get(username = usuario.username)
            cliente.groups.add(1)
            cliente.save()

            return redirect('index')

    else:
        f = CustomUserCreationForm()

    return render(request, 'registration/registro.html', {'form': f})
#suscripcion
def agregar_suscriptor(request, id):
    usuario = User.objects.get(id=id)
    usuario.groups.add(4)
    usuario.save()
    return redirect('index')

def subscripcion(request):
    data = {
        'form' : DonacionForm()
    } 
    if request.method == 'POST':
        formulario = DonacionForm(request.POST)
        if formulario.is_valid():
            Nombre = formulario.cleaned_data['Nombre']
            Email = formulario.cleaned_data['Email']
            Monto = formulario.cleaned_data['Monto']
        
    return render(request, 'core/subscripcion.html', data)

def status(request):
    user = User.objects.get(id=request.user.id)
    usuario = user.groups.filter(name='subscriptor').exists()
    data = {
        'usuario' : usuario
    }
    return render(request, 'core/status.html', data )

#Paypal
def ordercomplete(request):
    return render(request, 'core/order-complete.html')

def usuario(request):
    return render(request, 'core/usuario.html')

def quitar_usuario_de_grupo(request, id):

    usuario = User.objects.get(id=id)
    grupo = Group.objects.get(id=1)
    usuario.groups.remove(4)
    return redirect('status')



def detallepedido(request, id):
    pedido = Pedido.objects.get(id = id)
    lineapedido = LineaPedido.objects.filter(pedido=id)

    data = {
        'pedido': pedido,
        'lineapedido': lineapedido
    }

    return render(request, 'core/detallepedido.html', data)



def gallery(request):
    pedido = Pedido.objects.all()
    es_admin = request.user.is_staff

    data = {
        'LineaPedido' : pedido,   
        'es_admin': es_admin,
  
    }
    return render(request, 'core/gallery.html', data)


#Carrito

#seguimiento
def contacto_admin(request):
    # Verificar si el usuario es administrador
    es_admin = request.user.is_staff

    # Si es administrador, mostrar todos los contactos
    if es_admin:
        contactos = Contacto.objects.all()
    # Si no es administrador, mostrar solo los contactos del usuario actual
    else:
        contactos = Contacto.objects.filter(correo=request.user.email)

    # Renderizar la plantilla con los datos necesarios
    return render(request, 'core/contacto_admin.html', {'contactos': contactos, 'es_admin': es_admin})

def historial(request):
   lineas_pedido = LineaPedido.objects.filter(user=request.user)  # Filtrar por el usuario actual
   es_admin = request.user.is_staff
   if es_admin:
        pedidos = LineaPedido.objects.all()
   else:

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block contenido %}
<script>
    function eliminar_Productos(id){
        swal.fire({
            "title" : "¿estas seguro?",
            "text" : "esta accion no se puede deshacer",
            "icon" : "question",
            "showCancelButton" : true,
            "cancelButtonText" : "No, Cancelar",
            "confirmButtonText" : "Si, Eliminar",
            "reverseButtons" :true
        })
        .then(function(result){
            if(result.isConfirmed){
                window.location.href = "/eliminar-productos/"+id+"/"
            }

        })

    }
</script>

	<!-- hero area -->
	<div class="hero-area ">
		<div class="container">
			<div class="row">
				<div class="col-lg-9 offset-lg-2 text-center">
					<div class="hero-text">
						<div class="hero-text-tablecell">
							<p class="subtitle">Tu siguiente felicidad</p>
							<h1>Ferremax</h1>
							<div class="hero-btns">
								<a href="{% url 'shop' %}"  class="boxed-btn">Catalogo</a>
								<a href="{% url 'contact' %}" class="bordered-btn">¿Necesitas ayuda?, ¡Contactanos!</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end hero area -->

	<!-- features list section -->
	<div class="list-section pt-80 pb-80">
		<div class="container">

			<div class="row">
				<div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
					<div class="list-box d-flex align-items-center">
						<div class="list-icon">
							<i class="fas fa-shipping-fast"></i>
						</div>
						<div class="content">
							<h3>Envio gratis</h3>
							<p>Por compras superiores a $49.990</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
					<div class="list-box d-flex align-items-center">
						<div class="list-icon">
							<i class="fas fa-phone-volume"></i>
						</div>
						<div class="content">
							<h3>Soporte 24/7</h3>
							<p>Obten ayuda a cualquier hora que necesites</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<div class="list-box d-flex justify-content-start align-items-center">
						<div class="list-icon">
							<i class="fas fa-sync"></i>
						</div>
						<div class="content">
							<h3>¿Necesitas un Reembolso?</h3>
							<p>Obten tu reembolso dentro de 4 dias habiles!</p>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
	<!-- end features list section -->
	<!-- product section -->
	<div class="product-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="section-title">	
						<h3><span class="orange-text">Nuestros</span> Productos</h3>
						<p>Calidad garantizada</p>
						{% if user_is_contador %}
                        <a href="{% url 'registrar_entrega_pedido' %}" class="btn btn-primary">Botón para contadores</a>
                         {% endif %}
					</div>
				</div>
			</div>
				{% load humanize %}
			<div class="row">
				{% for aux in entity %}
				{% if aux.precio > 0 %}

				<div class="col-lg-4 col-md-6 text-center">
					<div class="single-product-item">
						<div class="product-image">
							{% if aux.imagen %}
							<a href="{% url 'singleproduct' aux.id %}"><img src="{{ aux.imagen.url }}" alt=""></a>
							{% endif %}
						</div>
						<h3>{{ aux.nombre | capfirst}}</h3>
						
						{% if user.is_authenticated %}

						<div class="pricing">
							<p class="price">$<span class="mr-2 price-dc" > {{ aux.precio }} </p>
						</div>	
						{% else %}
						<div class="pricing">
							<p class="price">$<span class="mr-2 price-dc" > {{ aux.precio }}  </span></p>
						</div>	
						{% endif %}

						{% if admin.is_authenticated %}

						{% if aux.stock > 0 %}
						<span>Stock disponible</span>
						{% else %}
						<span>No hay stock </span>
						<a href="{% url 'carro:cart_add' aux.id %}" class="cart-btn"><i class="fas fa-shopping-cart"></i> Agregar al carrito</a>

						{% endif %}
<hr>
						{% if perms.core.change_producto %}
						<a href="{% url 'modificar_productos' aux.id %}" class="btn btn-info btn-sm">Modificar</a>
						{% endif %}
						{% if perms.core.delete_producto %}

						 <a href="#" onclick="eliminar_Productos({{ aux.id }})" class="btn btn-danger btn-sm">Eliminar</a>
<hr>
						 {% endif %}
						 <a href="{% url 'carro:cart_add' aux.id %}" class="cart-btn"><i class="fas fa-shopping-cart"></i> Agregar al carrito</a>

						{% else %}
						
						{% if aux.stock > 0 %}
						<span>Stock: disponible</span>
						<hr>
						<a href="{% url 'carro:cart_add' aux.id %}" class="cart-btn"><i class="fas fa-shopping-cart"></i> Agregar al carrito</a>

						{% else %}
						<span>No hay stock </span>

						{% endif %}

                        {% endif %}

						


					</div>
				</div>
				{% endif %}

			{% endfor %}
			{% if user.is_authenticated %} {% if perms.app.view_producto %}
			<a href="{% url 'listar_productos' %}" class="btn btn-primary " class="btn-center">Ver listado de productos</a>
			{% endif %}
			{% endif %}

			</div>

		</div>

	</div>

	<div>{% include 'core/paginator.html' %}</div>

	<!-- end product section -->

	<!-- cart banner section -->
	<section class="cart-banner pt-100 pb-100">
    	<div class="container">
        	<div class="row clearfix">
            	<!--Image Column-->
            	<div class="image-column col-lg-6">
                	<div class="image">
                    	<div class="price-box">
                        	<div class="inner-price">
                                <span class="price">
                                    <strong>15%</strong> <br> de descuento
                                </span>
                            </div>
                        </div>
                    	<img src="{% static 'core/img/fondo.jpg' %}" alt="">
                    </div>
                </div>
                <!--Content Column-->
                <div class="content-column col-lg-6">
                    <h4>suscribete</h4>
                    <div class="text">Dona para tener un 15% de descuento en todos los productos
								<br></br>
						
						<br>Registro: El usuario se inscribe proporcionando sus datos personales y método de pago.</br>
						
						<br>Selección del Plan: Se elige el tipo de suscripción (mensual, anual, etc.).</br>
						
						<br>Pago: Se realiza el pago correspondiente al periodo elegido.</br>
						
						<br>Renovación Automática: La suscripción se renueva automáticamente al final de cada periodo, a menos que el usuario decida cancelarla.</br>
					</div>
                    <!--Countdown Timer-->
                	<a href="{% url 'donacion' %}" class="cart-btn mt-3"><i class=""></i> SUSCRIBETE PINCHANDO AQUI</a>
				</div>
            </div>
        </div>
    </section>
    <!-- end cart banner section -->

	<!-- testimonail-section -->
	<div class="testimonail-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 offset-lg-1 text-center">
					<div class="testimonial-sliders">
						<div class="single-testimonial-slider">
							<div class="client-avater">
								<img src="{% static 'core/img/avaters/avatar2.png' %}" alt="">
							</div>
							<div class="client-meta">
								<h3>Marcelo Diaz <span>Dueño local</span></h3>
								<p class="testimonial-body">
									"Nuestros productos son tan buenos como yo en el campo"
								</p>
								<div class="last-icon">
									<i class="fas fa-quote-right"></i>
								</div>
							</div>
						</div>
						<div class="single-testimonial-slider">
							<div class="client-avater">
								<img src="{% static 'core/img/avaters/avatar1.png' %}" alt="">
							</div>
							<div class="client-meta">
								<h3>Camila Hernriquez <span>Gerente en tienda</span></h3>
								<p class="testimonial-body">
									" Nos gusta tratar a nuestros clientes con respeto, como si fueran nuestras propias familias "
								</p>
								<div class="last-icon">
									<i class="fas fa-quote-right"></i>
								</div>
							</div>
						</div>
						<div class="single-testimonial-slider">
							<div class="client-avater">
								<img src="{% static 'core/img/avaters/avatar3.png' %}" alt="">
							</div>
							<div class="client-meta">
								<h3>German Garmendia <span>Informatico</span></h3>
								<p class="testimonial-body">
									"Tenemos la capacidad de ayudar en cualquier tipo de problema que se les presente, ya sea sobre sistemas o sobre productos"
								</p>
								<div class="last-icon">
									<i class="fas fa-quote-right"></i>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end testimonail-section -->
	
	<!-- advertisement section -->
	<div class="abt-section mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-12">
					<div class="abt-bg">
						<a href="https://www.youtube.com/watch?v=rzaCboPGhxA" class="video-play-btn popup-youtube"><i class="fas fa-play"></i></a>
					</div>
				</div>
				<div class="col-lg-6 col-md-12">
					<div class="abt-text">
						<p class="top-sub">Junto a ti desde 1999</p>
						<h2>Somos <span class="orange-text">ferremax</span></h2>
						<p></p>
						<a href="{% url 'about' %}" class="boxed-btn mt-4">Deseas saber mas de Nosotros?</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end advertisement section -->



	<!-- logo carousel -->
	<div class="logo-carousel-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="logo-carousel-inner">
						<div class="single-logo-item">
							<img src="{% static 'core/img/company-logos/1.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'core/img/company-logos/2.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'core/img/company-logos/3.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'core/img/company-logos/4.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'core/img/company-logos/5.png' %}" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end logo carousel -->

{% endblock %}

core/templates/core/shop.html
{% extends 'core/base.html' %}
{% load static %}
{% block contenido %}

<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 offset-lg-2 text-center">
				<div class="breadcrumb-text">
					<p>Producto de primera calidad</p>
					<h1>Productos en Tienda</h1>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container">
<!-- end breadcrumb section -->
{% load humanize %}
<div class="row">
	{% for aux in entity %}
	{% if aux.precio > 0 %}

	<div class="col-lg-4 col-md-6 text-center">
		<div class="single-product-item">
			<div class="product-image">
				{% if aux.imagen %}
				<a href="{% url 'singleproduct' aux.id %}"><img src="{{ aux.imagen.url }}" alt=""></a>
				{% endif %}
			</div>
			<h3>{{ aux.nombre | capfirst}}</h3>
			
			{% if user.is_authenticated %}

			<div class="pricing">
				<p class="price"><span class="mr-2 price-dc" ><del> {{ aux.precio }} </del> </span>{{1700}}</p>
			</div>	
			{% else %}
			<div class="pricing">
				<p class="price"><span class="mr-2 price-dc" > {{ aux.precio }}  </span></p>
			</div>	
			{% endif %}

			{% if admin.is_authenticated %}

			{% if aux.stock > 0 %}
			<span>Stock: {{ aux.stock }}</span>
			{% else %}
			<span>No hay stock </span>
			<a href="{% url 'carro:cart_add' aux.id %}" class="cart-btn"><i class="fas fa-shopping-cart"></i> Agregar al carrito</a>

			{% endif %}
<hr>
			{% if perms.core.change_producto %}
			<a href="{% url 'modificar_productos' aux.id %}" class="btn btn-info btn-sm">Modificar</a>
			{% endif %}
			{% if perms.core.delete_producto %}

			 <a href="#" onclick="eliminar_Productos({{ aux.id }})" class="btn btn-danger btn-sm">Eliminar</a>
<hr>
			 {% endif %}

			

			{% endif %}

			


		</div>
	</div>
	{% endif %}

{% endfor %}
</div>
<!-- end products -->
		<div>{% include 'core/paginator.html' %}</div>

<!-- logo carousel -->
<div class="logo-carousel-section">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="logo-carousel-inner">
					<div class="single-logo-item">
						<img src="{% static 'core/img/company-logos/1.png' %}" alt="">
					</div>
					<div class="single-logo-item">
						<img src="{% static 'core/img/company-logos/2.png' %}" alt="">
					</div>
					<div class="single-logo-item">
						<img src="{% static 'core/img/company-logos/3.png' %}" alt="">
					</div>
					<div class="single-logo-item">
						<img src="{% static 'core/img/company-logos/4.png' %}" alt="">
					</div>
					<div class="single-logo-item">
						<img src="{% static 'core/img/company-logos/5.png' %}" alt="">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end logo carousel -->

{% endblock %}